[package]
name = "crokey-proc_macros"
version = "0.2.0"
authors = ["Canop <cano.petrole@gmail.com>"]
description = "proc macros for the crokey crate"
license = "MIT"
edition = "2018"

[dependencies]

[lib]
proc-macro = true
path = "mod.rs"
